Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,13 +1,10 @@
 steps:
 - name: 'gcr.io/cloud-builders/docker'
-  args: ['build', '-t', 'us-central1-docker.pkg.dev/eternal-petal-426611-m0/gcf-artifacts/quickstart-image', './app1' ]
+  args: ['build', '-t', 'us-central1-docker.pkg.dev/eternal-petal-426611-m0/gcf-artifacts/quickstart-image', './app1']
   id: 'Build Docker Image'
 
-  # images:
-  # - 'us-central1-docker.pkg.dev/eternal-petal-426611-m0/gke-repo/quickstart-image'
-
 - name: 'gcr.io/cloud-builders/docker'
-  args: ['push', 'us-central1-docker.pkg.dev/eternal-petal-426611-m0/gcf-artifacts/quickstart-image' ]
+  args: ['push', 'us-central1-docker.pkg.dev/eternal-petal-426611-m0/gcf-artifacts/quickstart-image']
   id: 'Push Docker Image'
 
 - name: 'google/cloud-sdk:latest'
@@ -16,10 +13,21 @@ steps:
   - -xe
   - -c
   - |
-    gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1
-    gcloud deploy apply --file deploy/dev.yaml --region=us-central1
-    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --skaffold-file=skaffold.yaml
+    set -e
+    if ! gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1; then
+      echo "Error applying pipeline.yaml" >&2
+      exit 1
+    fi
 
+    if ! gcloud deploy apply --file deploy/dev.yaml --region=us-central1; then
+      echo "Error applying dev.yaml" >&2
+      exit 1
+    fi
+
+    if ! gcloud deploy releases create "app-release-${SHORT_SHA}" --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --skaffold-file=skaffold.yaml; then
+      echo "Error creating release" >&2
+      exit 1
+    fi
 
 options:
   logging: CLOUD_LOGGING_ONLY
